# Generated by Django 4.2.9 on 2025-12-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SIM', '模拟账号'), ('REAL', '真实账号')], default='SIM', max_length=10, verbose_name='账号模式')),
                ('market_type', models.CharField(choices=[('US_STOCK', '美股'), ('CN_A', 'A股'), ('HK_STOCK', '港股'), ('CRYPTO', '加密货币')], max_length=20, verbose_name='市场类型')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='账户名称')),
                ('currency', models.CharField(choices=[('USD', '美元'), ('CNY', '人民币'), ('HKD', '港币'), ('USDT', 'USDT')], max_length=10, verbose_name='币种')),
                ('start_cash', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='起始资金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_accounts', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '市场账户',
                'verbose_name_plural': '市场账户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='标的代码')),
                ('name', models.CharField(max_length=200, verbose_name='公司/资产全名')),
                ('asset_class', models.CharField(choices=[('US_STOCK', '美股'), ('HK_STOCK', '港股'), ('CRYPTO', '加密货币')], max_length=20, verbose_name='资产类别')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='行业分类')),
                ('exchange', models.CharField(blank=True, choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('HKEX', 'HKEX'), ('BINANCE', 'Binance'), ('COINBASE', 'Coinbase'), ('OTHER', '其他')], max_length=20, verbose_name='交易所')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='core.marketaccount', verbose_name='账户')),
            ],
            options={
                'verbose_name': '标的主档',
                'verbose_name_plural': '标的主档',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='股票代码')),
                ('side', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出')], max_length=4, verbose_name='交易方向')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='价格')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='手续费')),
                ('executed_at', models.DateTimeField(verbose_name='执行时间')),
                ('thesis', models.TextField(verbose_name='交易理论依据')),
                ('review', models.TextField(blank=True, verbose_name='复盘')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='core.marketaccount', verbose_name='账户')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='core.security', verbose_name='证券')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='CashAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='调整日期')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正数为入金，负数为出金', max_digits=15, verbose_name='调整金额')),
                ('reason', models.TextField(verbose_name='调整原因')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='adjustments/%Y/%m/%d/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.marketaccount', verbose_name='账户')),
            ],
            options={
                'verbose_name': '资金调整',
                'verbose_name_plural': '资金调整',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除')], max_length=10, verbose_name='操作')),
                ('model_type', models.CharField(max_length=50, verbose_name='模型类型')),
                ('model_id', models.IntegerField(verbose_name='模型ID')),
                ('changes', models.TextField(blank=True, verbose_name='变更内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['account', 'asset_class'], name='core_securi_account_5f8964_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['account', 'sector'], name='core_securi_account_68f6b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='security',
            unique_together={('account', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='marketaccount',
            index=models.Index(fields=['owner', 'mode'], name='core_market_owner_i_1e12b1_idx'),
        ),
        migrations.AddIndex(
            model_name='marketaccount',
            index=models.Index(fields=['owner', 'market_type'], name='core_market_owner_i_0de41b_idx'),
        ),
        migrations.AddIndex(
            model_name='cashadjustment',
            index=models.Index(fields=['account', 'date'], name='core_cashad_account_3b2e20_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_type', 'model_id'], name='core_auditl_model_t_bfd28e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx'),
        ),
    ]
