# Generated by Django 4.2.9 on 2025-12-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='trade_attachments/%Y/%m/%d/', verbose_name='文件')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.trade', verbose_name='交易')),
            ],
            options={
                'verbose_name': '交易附件',
                'verbose_name_plural': '交易附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
