# Generated by Django 4.2.9 on 2025-12-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tradeattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-executed_at', '-id'], 'verbose_name': '交易记录', 'verbose_name_plural': '交易记录'},
        ),
        migrations.RemoveField(
            model_name='trade',
            name='review',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='thesis',
        ),
        migrations.AddField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, help_text='支持 Markdown 格式', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='数量'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', '-executed_at'], name='core_trade_account_21ed44_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'symbol'], name='core_trade_account_468215_idx'),
        ),
    ]
