# Generated by Django 4.2.9 on 2025-12-28 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_trade_options_remove_trade_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-traded_at', '-id'], 'verbose_name': '交易记录', 'verbose_name_plural': '交易记录'},
        ),
        migrations.RemoveIndex(
            model_name='security',
            name='core_securi_account_5f8964_idx',
        ),
        migrations.RemoveIndex(
            model_name='security',
            name='core_securi_account_68f6b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='core_trade_account_21ed44_idx',
        ),
        migrations.RemoveIndex(
            model_name='trade',
            name='core_trade_account_468215_idx',
        ),
        migrations.RemoveField(
            model_name='security',
            name='asset_class',
        ),
        migrations.RemoveField(
            model_name='security',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='executed_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='side',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='symbol',
        ),
        migrations.AddField(
            model_name='security',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', '股票'), ('ETF', 'ETF'), ('CRYPTO', '加密货币')], default='US_STOCK', max_length=20, verbose_name='资产类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('OPEN_LONG', '开多'), ('CLOSE_LONG', '平多'), ('OPEN_SHORT', '开空'), ('CLOSE_SHORT', '平空')], default=1, max_length=20, verbose_name='交易动作'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='traded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='core.security', verbose_name='标的'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['account', 'asset_type'], name='core_securi_account_ef94e5_idx'),
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['account', 'symbol'], name='core_securi_account_d9e4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', '-traded_at'], name='core_trade_account_b2fcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'security'], name='core_trade_account_44840a_idx'),
        ),
    ]
