# Generated by Django 4.2.9 on 2025-12-28 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.marketaccount', verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.security', verbose_name='标的'),
        ),
    ]
