# Generated by Django 4.2.9 on 2025-12-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trade_account_alter_trade_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='filled_at',
            field=models.DateTimeField(blank=True, help_text='订单成交的时间', null=True, verbose_name='成交时间'),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('PENDING', '待成交'), ('FILLED', '已成交'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'status'], name='core_trade_account_8e83ef_idx'),
        ),
    ]
