# Generated by Django 4.2.9 on 2025-12-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trade_filled_at_trade_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='traded_at',
            field=models.DateTimeField(blank=True, help_text='实际交易时间，PENDING订单可为空', null=True, verbose_name='交易时间'),
        ),
    ]
